spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    host: 192.168.56.10
  session:
    store-type: redis
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1


server:
  port: 20000
  servlet:
    session:
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: '*'
